98 include an alternate path for test data download
EnzymeFunctionInitiative/EST pull request #99
Opened 2024-11-19 19:59 UTC by rbdavid

- Added improved argument handling to tests/test_env.sh. 
- Enabled testing input data to be downloaded to an EST repo external location. 
- Wrote a first draft of documentation for this new testing functionality.

2024-11-19 22:49 UTC, rbdavid commented
Ah, documentation for testing is also in docs/source/guides/testing.rst. I should update this file with equivalent if not the same text as the README file in the tests/ subdir.

2024-11-20 20:49 UTC, rbdavid commented
Doh! The changes to the test.docker.config files don't like local paths. It requires global paths. Fixing now.

2024-11-21 15:18 UTC, rbdavid commented
The `05_colorssn_uniprot.sh` test fails for singularity config files. Specifically: 

```
Executing tests in '05_colorssn_uniprot.sh'
Wrote params to '/tmp/efi_tests/results0/test_results_colorssn_uniprot/params.yml'
Nextflow 24.10.1 is available - Please consider updating your version to it

 N E X T F L O W   ~  version 24.04.4

Launching `pipelines/colorssn/colorssn.nf` [focused_almeida] DSL2 - revision: f9c1c49c85

[-        ] process > color_and_retrieve:get_ssn_id_info              -
[-        ] process > color_and_retrieve:compute_clusters             -
[-        ] process > color_and_retrieve:get_ssn_id_info              [  0%] 0 of 1
[-        ] process > color_and_retrieve:compute_clusters             -
executor >  local (1)
[f6/9f5510] process > color_and_retrieve:get_ssn_id_info              [  0%] 0 of 1
[-        ] process > color_and_retrieve:compute_clusters             -
[-        ] process > color_and_retrieve:get_id_list                  -
executor >  local (1)
[f6/9f5510] process > color_and_retrieve:get_ssn_id_info              [100%] 1 of 1, failed: 1 ✘
[-        ] process > color_and_retrieve:compute_clusters             -
[-        ] process > color_and_retrieve:get_id_list                  -
[-        ] process > color_and_retrieve:get_fasta                    -
[-        ] process > color_and_retrieve:color_ssn                    -
[-        ] process > color_and_retrieve:get_annotated_mapping_tables -
[-        ] process > color_and_retrieve:get_conv_ratio_table         -
[-        ] process > color_and_retrieve:get_cluster_stats            -
Pulling Singularity image docker://enzymefunctioninitiative/efi-est:latest [cache /tmp/efi_tests/results0/test_results_colorssn_uniprot/colorssn_work/singularity/enzymefunctioninitiative-efi-est-latest.img]
WARN: Singularity cache directory has not been defined -- Remote image will be stored in the path: /tmp/efi_tests/results0/test_results_colorssn_uniprot/colorssn_work/singularity -- Use the environment variable NXF_SINGULARITY_CACHEDIR to specify a different location
ERROR ~ Error executing process > 'color_and_retrieve:get_ssn_id_info'

Caused by:
  Process `color_and_retrieve:get_ssn_id_info` terminated with an error exit status (255)


Command executed:

  perl /home/rbdavid/Scripts/git/EST/pipelines/colorssn/../shared/perl/ssn_to_id_list.pl --ssn ssn.xgmml --edgelist edgelist.txt --index-seqid index_seqid_map.txt         --id-index id_index_map.txt --seqid-source-map seqid_source_map.txt

Command exit status:
  255

Command output:
  (empty)

Command error:
  WARNING: skipping mount of /home/rbdavid/Scripts/git/EST/tests/test_data: stat /home/rbdavid/Scripts/git/EST/tests/test_data: no such file or directory
  FATAL:   container creation failed: mount /home/rbdavid/Scripts/git/EST/tests/test_data->/home/rbdavid/Scripts/git/EST/pipelines/colorssn/../../tests/test_data error: while mounting /home/rbdavid/Scripts/git/EST/tests/test_data: mount source /home/rbdavid/Scripts/git/EST/tests/test_data doesn't exist

Work dir:
  /tmp/efi_tests/results0/test_results_colorssn_uniprot/colorssn_work/f6/9f5510cd87d7a4460e14d752c27ef2

Tip: you can replicate the issue by changing to the process work dir and entering the command `bash .command.run`

 -- Check '/tmp/efi_tests/results0/test_results_colorssn_uniprot/colorssn_nextflow.log' file for details
```

Seems to be that singularity configs are trying to mount the assumed --data-dir path of `/home/rbdavid/Scripts/git/EST/tests/test_data`. Updating that config file now.

2024-11-21 15:49 UTC, rbdavid commented
Both test.docker.config and test.singularity.config testing runs pass with no errors on my local desktop. Still need to test this branch on HPC machines.

2024-12-11 15:45 UTC, nilsoberg requested changes

2024-12-11 15:45 UTC, nilsoberg commented on tests/runtests.sh
> +#bash "tests/modules/05_colorssn_uniprot.sh" $EFI_TEST_RESULTS_DIR $CONFIG_FILE
This line was in `nextflow-test` before this branch, and shouldn't have been there.  It can be deleted.

2024-12-11 15:45 UTC, nilsoberg commented on tests/README.md
> +> Assuming that the MySQL dataset and database have been setup and BLAST database files have been installed in `tests/test_data/mysql`, the MySQL environment can be set up by running `source tests/te
Delete this block quote (lines 36-39) and replace with the first part of the sentence (i.e. `Giving a value of "mysql" expects that the full EFI database files are stored locally.`).  The code should work correctly if the MySQL database is set up.  It's just not something we've tested yet.

2024-12-11 15:45 UTC, nilsoberg commented on tests/README.md
We need to unify the `docs/source/guides/testing.rst` and this README and have one or the other.  I think merging this text into `docs/source/guides/testing.rst` would be best, because the usage described in this file is what an end-user will do and thus should be part of the docs.  The README can then describe how to add or disable tests and things that a dev would need to know to, in the future.  For now, we can delete this file.

2024-12-11 15:45 UTC, nilsoberg commented on conf/colorssn/test.docker.config
Off hand I don't see a way around putting `$EFI_TEST_DATA_DIR` in the `containerOptions`.  However, I wonder what happens if that environment variable isn't set.  Is it possible for the container to execute without the test environment being sourced?

2024-12-13 20:37 UTC, rbdavid commented on tests/runtests.sh
> +#bash "tests/modules/05_colorssn_uniprot.sh" $EFI_TEST_RESULTS_DIR $CONFIG_FILE
Removed those lines.

2024-12-13 20:39 UTC, rbdavid commented on tests/README.md
> +> Assuming that the MySQL dataset and database have been setup and BLAST database files have been installed in `tests/test_data/mysql`, the MySQL environment can be set up by running `source tests/te
Done.

2024-12-16 15:59 UTC, rbdavid commented on tests/README.md
I've pushed a draft of `testing.rst`. Please give it a read when you can.

2024-12-16 16:07 UTC, rbdavid commented on conf/colorssn/test.docker.config
If the `test_env.sh` script is never run, then the `runtests.sh` script exits with the error message `"Test environment variables not found, please run 'source tests/test_env.sh"`. 

https://github.com/EnzymeFunctionInitiative/EST/blob/063954bdb0063da412bf7a582a315e8c03d28ccc/tests/runtests.sh#L38
checks for some (but not all) environment variables that get defined in `test_env.sh`. Maybe we should add more checks for other env vars too? or simplify the checks?

2024-12-16 16:32 UTC, rbdavid commented on tests/README.md
Does deleting the README file need to happen though? I think having the necessary information for running the tests in two places isn't an issue. As you said, the README should hold more dev-focused information, so I can add the info about disabling tests in addition to the basic usage info.

2024-12-16 16:32 UTC, rbdavid commented on conf/colorssn/test.docker.config
In regards to the $EFI_TEST_DATA_DIR env variable used in the nextflow `containerOptions` field, these nextflow configurations do recognize environment variables as well as the default nextflow variables. 

I think this can be used to great effect for setting up the EFI pipelines on HPC machines. Env variables can be defined in the batch scripts and machine-specific nextflow config files can use those vars.

2024-12-20 01:48 UTC, nilsoberg approved these changes
Update README to point to `docs/source/guides/testing.rst` and it looks good.

2024-12-20 17:33 UTC, merged